#! /bin/bash
sudo docker-compose down;
sudo docker-compose build;
sudo docker-compose up -d;

#Setting up CMD Files
sudo docker exec -it dockerdrive_ds_1 bash cmdfile;
sudo docker exec -it dockerdrive_nginx_1 bash cmdfile;
