#! /bin/bash
#Install Environment on a new ubuntu machine ----------
cd envsetup
sudo bash setup-env;
cd ..

### Download and unzip the deployment files: ----------

DIRNAME="master";
DIRPATH="https://github.com/ShoabSaadat/dockerdrive/archive/";
WORKINGFOLDERNAME="DockerDrive"

wget $DIRPATH/$DIRNAME.zip;
sudo unzip -o ./$DIRNAME.zip -d ./$DIRNAME;
sudo mv ./$DIRNAME/dockerdrive-$DIRNAME/ ./DD;
sudo rm -rf $DIRNAME;
sudo mv ./DD ./$WORKINGFOLDERNAME;

sudo chmod 777 ./$WORKINGFOLDERNAME/;
sudo rm -rf ./$DIRNAME.zip;

Install the necessary directories: --------------------
sudo mkdir -p -m 777 ./$WORKINGFOLDERNAME/shiny
sudo mkdir -p -m 777 ./$WORKINGFOLDERNAME/plumber/plumber1
sudo mkdir -p -m 777 ./$WORKINGFOLDERNAME/lemp/www/
sudo mkdir -p -m 777 ./$WORKINGFOLDERNAME/lemp/nginx/log
sudo mkdir -p -m 777 ./$WORKINGFOLDERNAME/lemp/mariadb
sudo touch ./$WORKINGFOLDERNAME/lemp/nginx/log/error.log
sudo touch ./$WORKINGFOLDERNAME/lemp/nginx/log/access.log

### Run Docker ---------------------------------------
cd ./$WORKINGFOLDERNAME;
bash rundocker;

##NOW setup dropbox:--------------------------------------------
#cd ~;
#wget -O dropbox.tar.gz "http://www.dropbox.com/download/?plat=lnx.x86_64";
#sudo apt-get install nautilus-dropbox;
#tar -xvzf dropbox.tar.gz;
#.dropbox-dist/dropboxd &
#sudo dropbox autostart y;
##Setting permissions right
#sudo chown "$USER" "$HOME"
#sudo chown -R "$USER" ~/Dropbox ~/.dropbox
#sudo chattr -R -i ~/Dropbox
#sudo chmod -R u+rw ~/Dropbox ~/.dropbox


