#! /bin/bash
sudo dd if=/dev/zero of=/root/myswapfile bs=1M count=1024;
sudo ls -l /root/myswapfile;
sudo chmod 600 /root/myswapfile;
sudo mkswap /root/myswapfile;
sudo swapon /root/myswapfile;

sudo vim /etc/fstab 
#then add following line to make it autorestart: 
#/root/myswapfile               swap                    swap    defaults        0 0;

#verify:
sudo swapon -s;
sudo free -k;

swapoff -a;
swapon -a;


###Link:
#https://www.thegeekstuff.com/2010/08/how-to-add-swap-space/
